// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuNzfpOw3350zWMp4IHszQOJ4iqyIyPWE',
    appId: '1:1028615341233:web:43d0eda45e7ead0e9cce90',
    messagingSenderId: '1028615341233',
    projectId: 'test-db-beb1f',
    authDomain: 'test-db-beb1f.firebaseapp.com',
    storageBucket: 'test-db-beb1f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEAfQ3ebR53X4GLYwkJjIQKbed8UGt4zA',
    appId: '1:1028615341233:android:c69d37b6569337cf9cce90',
    messagingSenderId: '1028615341233',
    projectId: 'test-db-beb1f',
    storageBucket: 'test-db-beb1f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaYpNaeGZi_JKrEQeCVnfT86o2atmO_jQ',
    appId: '1:1028615341233:ios:d3872c9b78c55c7c9cce90',
    messagingSenderId: '1028615341233',
    projectId: 'test-db-beb1f',
    storageBucket: 'test-db-beb1f.appspot.com',
    androidClientId: '1028615341233-5g6tmult9no422uqskrpdin1daluvrnt.apps.googleusercontent.com',
    iosClientId: '1028615341233-b9ehka70kfigcgjclbcblpjqr5rle8k1.apps.googleusercontent.com',
    iosBundleId: 'com.example.testApp',
  );
}
